### ISSUE TITLE
Setup guide request/Cannot find module 'coffee-script/register'

### ISSUE THREAD

**Issue by yarnball** [slang800/instagram-screen-scrape#19]
Hi,

I have a list (I can put it in .csv or .json format) of MediaID's I'd like to get the comment content from.

As there is no setup guide, I may have some of this wrong.

`npm g -i`

Then when I tried running:
`instagram-screen-scrape comments --post 0qPcnuI4Pr`

This renders the following error:

```
MacBook-Pro-3:CommentNPM mac1$ ls
LICENSE     Makefile    README.md   bin     lib     package.json    test
MacBook-Pro-3:CommentNPM mac1$ instagram-screen-scrape 
module.js:327
    throw err;
    ^

Error: Cannot find module 'coffee-script/register'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/instagram-screen-scrape/bin/index.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

How can I fix this error?

**Comment by notslang** [comment]
There's a setup guide here: https://www.npmjs.com/package/instagram-screen-scrape/tutorial

But you basically just need to do: `npm install instagram-screen-scrape -g`

**Comment by yarnball** [comment]
Thank you @slang800 that guide is a great help- maybe post a link on the repo too.

How would I do the scrape for a list/batch of MediaID's? I am currently doing it individually which is very slow. Ideally I can just write the comments to a text file or something.

Thanks
