### ISSUE TITLE
Instagram returns 404

### ISSUE THREAD

**Issue by masterxyth** [slang800/instagram-screen-scrape#32]
Hi,

trying to scrape but getting this error:
```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Instagram returned status code: 404)
    at InstagramPosts.emit (events.js:163:17)
    at Stream.<anonymous> (/usr/local/lib/node_modules/instagram-screen-scrape/lib/posts.js:69:22)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/instagram-screen-scrape/lib/util.js:25:24)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/usr/local/lib/node_modules/instagram-screen-scrape/node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)`

**Comment by causztic** [comment]
Instagram has removed the API endpoint that the API library was using.

**Comment by enderim** [comment]
So, the library is useless anymore?

**Comment by causztic** [comment]
I've developed my own library to replace this! It is able to retrieve posts and videos.

repo is: https://github.com/causztic/night-stalker
